# Generated by Django 4.1.7 on 2023-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
