# Generated by Django 4.1.7 on 2023-04-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_rate_review_delete_game_publisher_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1023)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Publisher_FAQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2047)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_FAQ', to='game.game')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_FAQ', to='publisher.publisher')),
            ],
            options={
                'db_table': 'publisher_faq',
            },
        ),
        migrations.CreateModel(
            name='Publisher_Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1023)),
                ('time', models.DateTimeField(auto_now=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_document', to='game.game')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_document', to='publisher.publisher')),
            ],
            options={
                'db_table': 'publisher_document',
            },
        ),
        migrations.CreateModel(
            name='Game_Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher')),
            ],
            options={
                'db_table': 'game_publisher',
            },
        ),
    ]
