# Generated by Django 4.1.7 on 2023-04-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1023)),
                ('player_number', models.CharField(max_length=20)),
                ('play_time', models.CharField(max_length=20)),
                ('age_range', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1023)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Game_Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='game.game')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_id', to='game.publisher')),
            ],
            options={
                'db_table': 'game_publisher',
            },
        ),
    ]
