# Generated by Django 4.1.7 on 2023-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rate_review_delete_game_publisher_delete_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='game',
            name='play_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_number',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='published_year',
            field=models.IntegerField(null=True),
        ),
    ]
