# Generated by Django 4.1.7 on 2023-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
    ]
