# Generated by Django 4.1.7 on 2023-04-10 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_remove_game_age_range_remove_game_play_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=1023, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_collection', to='game.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('number', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1023, null=True)),
                ('image', models.CharField(max_length=2047, null=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_component', to='collection.collection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_component', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'component',
            },
        ),
    ]
