# Generated by Django 4.1.7 on 2023-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='play_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
