# Generated by Django 4.1.7 on 2023-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_play_time_collection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
